name: NEXT JS CICD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: next
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/payroll:latest

  deploy:
    needs: build
    runs-on: next
    steps:
      - name: pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/payroll:latest

      - name: delete pre exist container
        run: docker rm -f payroll_container

      - name: create and run docker container
        run: docker run -d -p 3000:80 --name payroll_container ${{ secrets.DOCKER_HUB_USERNAME }}/payroll