name: CI/CD Next JS Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout version node
      uses: actions/checkout@v3

    - name: Authenthicate with Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD}} 

    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-test:latest
